### ISSUE TITLE
Make groupped checkboxes

### ISSUE THREAD

**Issue by sergeysova** [AZaviruha/react-form-generator#2]
I want to make groupped checkboxes. But how?

same as:

``` html
<input type="checkbox" name="form1[variants][]" value="variant1" />
<input type="checkbox" name="form1[variants][]" value="variant2" />
<input type="checkbox" name="form1[variants][]" value="variant3" />
<input type="checkbox" name="form1[variants][]" value="variant4" />
```

and in state:

``` javascript
this.state.value.form1.variants == [ "variant1", "variant2", "variant3", "variant4" ]; // if all checked
```

What fields and layout must?

**Comment by AZaviruha** [comment]
Hi!
I'm going to write a tutorial for adding custom components. Your case is a good candidate, so i'll use it as example. 
I plan to publish this tutorial at nearest weekend. Is this an allowable delay for you?

**Comment by sergeysova** [comment]
@AZaviruha yes. I can wait. This functionality is very necessary for me

**Comment by sergeysova** [comment]
@AZaviruha send me the link to your tutorial after you write it, please

**Comment by AZaviruha** [comment]
@LestaD, i just finished example of custom component

Here is componet's code: https://github.com/AZaviruha/react-form-generator/blob/master/demo/client/js/main.js#L19

and here is how to register custom component, so generator will know about it:
https://github.com/AZaviruha/react-form-generator/blob/master/demo/client/js/main.js#L105

I'm still working on article, so for now look at this source code. I think, I'll finish tutorial today.

**Comment by sergeysova** [comment]
@AZaviruha thats great!
How can i use ES6?

``` ES6
// Ex.:
class GroupCheckbox extends FormGenerator.Base {}

// Or using decorators
@FormGenerator
class GroupCheckbox extends React.Component {}
```

**Comment by AZaviruha** [comment]
@LestaD , _react-form-generator_ does not have any special support for ES6 classes. 

Maybe you can use BabelJS to produce ES5-compatible code from your ES6  classes.

**Comment by sergeysova** [comment]
@AZaviruha i use babel to compile before build react-based project. But all code in project was wrote in ES6

**Comment by AZaviruha** [comment]
@LestaD here is an article about custom components: http://react-form-generator.readthedocs.org/en/latest/intermediate/custom-components/

**Comment by sergeysova** [comment]
@AZaviruha thank you!
